library(gplots)
args <- commandArgs(trailingOnly = TRUE)
data=read.table(args[1],header=T)
#dim(data)
data=as.matrix(as.matrix(data)[,3:dim(data)[2]])
data=apply(data, 2, as.numeric)

#class(data)
print(quantile(data,0.9)[1])
my_palette <- colorRampPalette(c("white", "green3"))(n = 49)
colors = c(seq(0,quantile(data,0.95)[1],length=25),seq(quantile(data,0.95)[1]+0.1,(quantile(data,0.95)[1]+0.1)*2,length=25))
png(args[2],res=300,width=800,height=1000)
heatmap.2(data, Rowv=NA, Colv=NA, col=my_palette,breaks=colors, margins=c(0.01,0.01),symm=F,symkey=F,symbreaks=T, key=F, labRow=F, labCol=F, keysize=0.001, scale="none", density.info="none", trace="none", dendrogram='none')
dev.off()
